// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.AlphaBot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainRightTalon;
    public static CANTalon driveTrainLeftTalon;
    public static RobotDrive driveTrainCANDrive;
    public static SpeedController linearActuatorLinear;
    public static Ultrasonic sonarSensor;
    public static PowerDistributionPanel powerManagementPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightTalon = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "RightTalon", driveTrainRightTalon);
        
        driveTrainLeftTalon = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "LeftTalon", driveTrainLeftTalon);
        
        driveTrainCANDrive = new RobotDrive(driveTrainLeftTalon, driveTrainRightTalon);
        
        driveTrainCANDrive.setSafetyEnabled(true);
        driveTrainCANDrive.setExpiration(0.1);
        driveTrainCANDrive.setSensitivity(0.5);
        driveTrainCANDrive.setMaxOutput(1.0);

        linearActuatorLinear = new Talon(2);
        LiveWindow.addActuator("LinearActuator", "Linear", (Talon) linearActuatorLinear);
        
        sonarSensor = new Ultrasonic(0, 1);
        LiveWindow.addSensor("Sonar", "Sensor", sonarSensor);
        
        powerManagementPowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("PowerManagement", "PowerDistributionPanel", powerManagementPowerDistributionPanel);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
